services:
  - type: web
    name: camisas-api
    env: dotnet
    plan: free
    branch: main
    buildCommand: dotnet publish DSW_PROYECTO_PALACIO_CAMISAS_API/DSW_PROYECTO_PALACIO_CAMISAS_API.csproj -c Release -o publish
    startCommand: cd publish && ./DSW_PROYECTO_PALACIO_CAMISAS_API